export const WISHLIST_BOOKS_REQUEST = 'app/WishlistPage/WISHLIST_BOOKS_REQUEST';
export const WISHLIST_BOOKS_SUCCESS = 'app/WishlistPage/WISHLIST_BOOKS_SUCCESS';
export const WISHLIST_BOOKS_ERROR = 'app/WishlistPage/WISHLIST_BOOKS_ERROR';

export const REMOVE_REQUEST_REQUEST = 'app/WishlistPage/REMOVE_REQUEST_REQUEST';
export const REMOVE_REQUEST_SUCCESS = 'app/WishlistPage/REMOVE_REQUEST_SUCCESS';
export const REMOVE_REQUEST_ERROR = 'app/WishlistPage/REMOVE_REQUEST_ERROR';
